config/routes.rb
Karasys::Application.routes.draw do

  get "players/play"
  get "players/interval"
  get "players/done"

  get "songs/entry"
  get "songs/index"

  match "reservations/preview" => 'reservations#preview'
  match "reservations/search" => 'reservations#search'
  resources :reservations

end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
  belongs_to :song
  attr_accessible :reproduced, :song_id
end

app/models/song.rb
class Song < ActiveRecord::Base
  has_many :reservations
  attr_accessible :album, :artist, :name, :path, :title, :origin_path
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController

  def interval
    @next_reservations = Reservation.where(reproduced: false).order(:id)[0..4]

  end

  def play
    @now_reservation = Reservation.where(reproduced: false).order(:id).first
    if @now_reservation.nil?
      sleep 3
      redirect_to players_interval_path
      return
    end
    render :action => "play", :layout => false
  end

  def done
    @now_reservation = Reservation.where(reproduced: false).order(:id).first
    @now_reservation.reproduced = true
    @now_reservation.save
    redirect_to players_interval_path
  end

end

app/controllers/reservations_controller.rb
# encoding: utf-8

class ReservationsController < ApplicationController
  def index
    @reservations = Reservation.order(:id)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @reservations }
    end
  end

  def create
    @reservation = Song.find(params[:format]).reservations.build

    if @reservation.save
      redirect_to reservations_path, notice: '予約が完了しました．'
    else
      redirect_to reservations_path, notice: '予約に失敗しました．'
    end
  end

  def destroy
    @reservation = Reservation.find(params[:id])
    @reservation.destroy

    respond_to do |format|
      format.html { redirect_to reservations_url }
      format.json { head :no_content }
    end
  end

  def search
    @query = params[:q]
    if @query
      @songs = Song.where( " name like ? OR title like ? OR artist like ? OR album like ? ", "%#{@query}%", "%#{@query}%", "%#{@query}%", "%#{@query}%" )
    end
  end

  def preview
    @folder_path = Rails.root + "public/karadata"
    @files = []
    require 'find'
    exts = [".mp3", ".mp4", ".flv"]
    Find.find(@folder_path) {|f|
      # @files << f.gsub("#{Rails.root}/public","") if exts.include?(File.extname(f))
      @files << f if exts.include?(File.extname(f))
    }

    require 'audioinfo'
    @infolist = []
    AudioInfo.open(@files[0]) do |info|
      @infolist << info.artist   # or info["artist"]
      @infolist << info.title    # or info["title"]
      @infolist << info.length   # playing time of the file
      @infolist << info.bitrate  # average bitrate
      @infolist << info.to_h     # { "artist" => "artist", "title" => "title", etc... }
    end
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  def index
    @songs = Song.all
  end

  def entry
    Song.all.each do |song|
      song.destroy
    end
    Reservation.all.each do |reservation|
      reservation.destroy
    end

    row_folders = ["public/karadata_row/"]
    # txt_path = "#{Rails.root}/config/entry_folder.txt"
    # IO.readlines(txt_path).each do |line|
    #   row_folders << line.strip if line.size > 2
    # end
    use_folder = Rails.root + "public/karadata_use"
    FileUtils.rm_r( Dir.glob( use_folder ), {:force=>true} )
    FileUtils.mkdir_p("#{use_folder}") unless FileTest.exist?("#{use_folder}")

    files = []
    require 'find'
    exts = {".mp3" => true,
           ".mp4" => true}
    index = 1
    row_folders.each do |row_folder|
      Find.find(row_folder) {|src|
        file_ext = File.extname(src)
        if exts[file_ext]
          file_name = File.basename(src)
          mv_file_name = "#{use_folder}/#{index.to_s + file_ext}"
          FileUtils.move(src, mv_file_name)
          files << {:origin_path => src, :path => mv_file_name }
          index += 1
        end
      }
    end

    # render :text => files

    require 'audioinfo'
    files.each do |paths|
      AudioInfo.open(paths[:path]) do |info|
        paths[:metadata] = info.to_h
      end
    end
    files.each do |paths|
      neme = File.basename(paths[:origin_path])
      origin_path = paths[:origin_path].gsub("#{Rails.root}/public" ,"")
      path = paths[:path].gsub("#{Rails.root}/public" ,"")
      title = paths[:metadata]["title"]
      artist = paths[:metadata]["artist"]
      album = paths[:metadata]["album"]
      h = {:name => neme, :path => path, :title => title, :artist => artist, :album => album, :origin_path => origin_path}
      @song = Song.create h
    end
    redirect_to songs_index_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Karasys" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>

    <div class="navbar navbar-fluid-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="<%= reservations_path %>">Karasys</a>
          <div class="container-fluid nav-collapse">
            <ul class="nav">
              <li><%= link_to "予約確認", reservations_path %></li>
              <li><%= link_to "曲検索", reservations_search_path %></li>
              <li><%= link_to "曲一覧", songs_index_path %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
<!--         <div class="span3">
          <div class="well sidebar-nav">
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div>
        </div> -->
        <div class="span12">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <!-- <p>&copy; Company 2013</p> -->
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/players/interval.html.erb
<script type="text/javascript">
  mnt = 3; // 何秒後に移動するか？
  url = "<%= url_for players_play_path %>"; // 移動するアドレス
  function jumpPage() {
    location.href = url;
  }
  setTimeout("jumpPage()",mnt*1000)
</script>

<h1>Next Song!!</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>予約番号</th>
      <th>ファイル名</th>
      <th>曲名</th>
      <th>アーティスト</th>
      <th>アルバム</th>
    </tr>
  </thead>
  <tbody>
    <% @next_reservations.each_with_index do |reservations, index| %>
    <tr>
      <td><%= index + 1 %></td>
      <td><%= reservations.song.name %></td>
      <td><%= reservations.song.title %></td>
      <td><%= reservations.song.artist %></td>
      <td><%= reservations.song.album %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/players/play.html.erb
<script type="text/javascript">
  function redirect() {
    location.replace('<%= url_for players_done_path %>')
  }
</script>

<!-- <table class="table table-striped">
  <thead>
    <tr>
      <th>ファイル名</th>
      <th>曲名</th>
      <th>アーティスト</th>
      <th>アルバム</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= @now_reservation.song.name %></td>
      <td><%= @now_reservation.song.title %></td>
      <td><%= @now_reservation.song.artist %></td>
      <td><%= @now_reservation.song.album %></td>
    </tr>
  </tbody>
</table> -->
<% if File.extname(@now_reservation.song.name) == ".mp4" %>
  <video height="800" width="1200" src="<%= @now_reservation.song.path %>" controls="controls" preload="auto" autoplay="true"
    onended="redirect();">
<% elsif File.extname(@now_reservation.song.name) == ".mp3" %>
  <audio src="<%= @now_reservation.song.path %>" controls="true" preload="auto" autoplay="true"
    onended="redirect();">
<% end %>

app/views/reservations/_form.html.erb
<%= form_for(@reservation) do |f| %>
  <% if @reservation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@reservation.errors.count, "error") %> prohibited this reservation from being saved:</h2>

      <ul>
      <% @reservation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reservations/edit.html.erb
<h1>Editing reservation</h1>

<%= render 'form' %>

<%= link_to 'Show', @reservation %> |
<%= link_to 'Back', reservations_path %>

app/views/reservations/index.html.erb
<h1>予約状況確認</h1>
<br>
<%= link_to 'preview Reservation', reservations_preview_path %>

<table class="table table-striped">
  <thead>
    <tr>
      <th>予約番号</th>
      <th>ファイル名</th>
      <th>曲名</th>
      <th>アーティスト</th>
      <th>アルバム</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @reservations.each_with_index do |reservation, index| %>
    <% if !reservation.reproduced %>
      <tr>
        <td><%= index + 1 %></td>
        <td><%= reservation.song.name %></td>
        <td><%= reservation.song.title %></td>
        <td><%= reservation.song.artist %></td>
        <td><%= reservation.song.album %></td>
        <td>
          <%= link_to t('.destroy', default: t("helpers.links.destroy")),
            reservation_path(reservation),
            method: :delete,
            data: { confirm: t('.confirm', default: t("helpers.links.confirm", default: '削除してもよろしいですか？')) },
            class: 'btn btn-danger' %>
        </td>
      </tr>
    <% end %>
    <% end  %>
  </tbody>
</table>

app/views/reservations/new.html.erb
<h1>New reservation</h1>

<%= render 'form' %>

<%= link_to 'Back', reservations_path %>

app/views/reservations/preview.html.erb
<script type="text/javascript">
  function redirect() {
    location.replace('<%= url_for reservations_path %>')
  }
</script>

<%= @content %>
<br>
<%= @files[0] %>
<br>
<%= @infolist  %>

<div id='console'>
</div>

<video height="600" src="/karadata/青葉りんご/Love Flower ／ 青葉りんご(Nico - sm15832696).mp4" width="800" controls="controls" preload="auto"
  onended="redirect();">

app/views/reservations/search.html.erb
<h1>検索ページ</h1>
<br>

<div id="search_form_box">
  <%= form_tag :reservations_search, :class => "form-search" ,method: :get do %>
    <p><%= text_field_tag "q", params[:q], :placeholder => "曲名, アーティスト名, アルバム  etc..", :value => @query %>
    <%= submit_tag "検索", :class => "btn" %></p>
  <% end %>
</div>

<% if @songs.present? %>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>ファイル名</th>
        <th>曲名</th>
        <th>アーティスト</th>
        <th>アルバム</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @songs.each do |song| %>
        <tr>
          <td><%= song.name %></td>
          <td><%= song.title %></td>
          <td><%= song.artist %></td>
          <td><%= song.album %></td>
          <td>
            <%= link_to '予約',
              reservations_path(song),
              method: :post,
              data: { confirm: '予約しますか？' },
              class: 'btn btn-success' %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <h4>ここに検索結果が表示されます</h4>
<% end %>

app/views/reservations/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_reservation_path(@reservation) %> |
<%= link_to 'Back', reservations_path %>

app/views/songs/entry.html.erb
<h1>Songs#entry</h1>
<p>Find me in app/views/songs/entry.html.erb</p>

<table class="table table-striped">
  <thead>
    <tr>
      <th>ファイル名</th>
      <th>ファイルパス</th>
      <th>曲名</th>
      <th>アーティスト</th>
      <th>アルバム</th>
    </tr>
  </thead>
  <tbody>
    <% @songs.each do |song| %>
      <tr>
        <td><%= song.name %></td>
        <td><%= song.path %></td>
        <td><%= song.title %></td>
        <td><%= song.artist %></td>
        <td><%= song.album %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/songs/index.html.erb
<h2>登録内容</h2>

<table class="table table-striped">
  <thead>
    <tr>
      <th>ファイル名</th>
      <th>曲名</th>
      <th>アーティスト</th>
      <th>アルバム</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @songs.each do |song| %>
      <tr>
        <td><%= song.name %></td>
        <td><%= song.title %></td>
        <td><%= song.artist %></td>
        <td><%= song.album %></td>
        <td>
          <%= link_to '予約',
            reservations_path(song),
            method: :post,
            data: { confirm: '予約しますか？' },
            class: 'btn btn-success' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>